default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"

  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    release = firebase_app_distribution(
      app: "1:932071578923:android:ed5fdbcf8b06705297f96e",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "elmohamdiabdraboh51@gmail.com",
      release_notes: "First fastlane firebase distribution!!"
    )
  end
end